### ISSUE TITLE
Interesting Note About Compiling The Payload On New JVMs

### ISSUE THREAD

**Issue by ghost** [zhuowei/GhidraLog4Shell#2]

**Comment by zhuowei** [comment]
You can try adding `--add-opens` to the command line to [allow](https://stackoverflow.com/questions/44056405/whats-the-difference-between-add-exports-and-add-opens-in-java-9) it to [access](https://docs.oracle.com/javase/9/migrate/toc.htm#JSMIG-GUID-7BB28E4D-99B3-4078-BDC4-FC24180CE82B) private variables via reflection.

I've only tested this on 11.0.4, so I haven't noticed this. Sorry about that!

Edit: I've pushed a branch that works on Java 17. I tested on Ubuntu 21.04/`17.0.1+12-Ubuntu-121.04`. Let me know if this helps and I'll merge it.

**Comment by alexis-evelyn** [comment]
It appears the latest branch currently does not work, but the `--add-opens` flag does appears to work.

`java --add-opens java.base/java.util=ALL-UNNAMED -jar ~/executables/ghidra_10.1_PUBLIC/Ghidra/Features/Python/lib/jython-standalone-2.7.2.jar generate_jython_payload.py`

![Screenshot_20211216_164240](https://user-images.githubusercontent.com/6305346/146453274-dd1dc7fc-90eb-4f60-b201-0f2fef86e697.png)
